FROM python:3.5

ARG dept=57
ARG fichiergz=bano-${dept}.json.gz
# fichier gzip complet : full.sjson.gz

RUN apt-get update \
	&& apt-get -qy --no-install-recommends install \
		git \
		wget \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install cython
RUN pip install git+https://github.com/addok/addok
RUN pip install git+https://github.com/addok/addok-fr
RUN pip install git+https://github.com/addok/addok-france
RUN pip install git+https://github.com/addok/addok-trigrams

RUN wget "http://bano.openstreetmap.fr/data/${fichiergz}" \
	&& gunzip "${fichiergz}"

COPY local.py /app

ENV ADDOK_CONFIG_MODULE /app/local.py
ENV REDIS_HOST redis

CMD addok import *.json *.sjson

