FROM python:3.5

ARG full=
ARG dept=${full:-57}
ARG gzfile=${full:-bano-${dept}.json.gz}${full:+.sjson.gz}

RUN echo "${gzfile}"

RUN apt-get update \
	&& apt-get -qy --no-install-recommends install \
		git \
		wget \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install cython
RUN pip install git+https://github.com/addok/addok
RUN pip install git+https://github.com/addok/addok-fr
RUN pip install git+https://github.com/addok/addok-france
RUN pip install git+https://github.com/addok/addok-trigrams

RUN wget "http://bano.openstreetmap.fr/data/${gzfile}" \
	&& gunzip "${gzfile}"

COPY local.py /app

ENV ADDOK_CONFIG_MODULE /app/local.py
ENV REDIS_HOST redis

CMD addok import *json

