version: "2"

services:
  db:
    image: redis
  import:
    build:
      context: .
      dockerfile: Dockerfile-import
      args:
        - full=full
    links:
      - db:redis
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    links:
      - db:redis
    ports:
      - 7878:7878
